### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'p_signals'

### ISSUE THREAD

**Issue by mahmoodabed** [PatNS/ECG_IOT#1]
Traceback (most recent call last):
  File "hh.py", line 28, in <module>
    Seg = ECG_Segment(i)
  File "hh.py", line 19, in ECG_Segment
    bfunc = np.asarray(record.p_signals)
AttributeError: 'tuple' object has no attribute 'p_signals'

**Comment by mahmoodabed** [comment]
I could fix this issue by doing this:
`record = wfdb.rdsamp(ECG_Signal_file)
 `
`p_signals, _ = wfdb.rdsamp(ECG_Signal_file)
  `
`bfunc = np.asarray(p_signals)`
