### ISSUE TITLE
ValueError: Shape of passed values is (18000, 1), indices imply (1000, 1)

### ISSUE THREAD

**Issue by mahmoodabed** [PatNS/ECG_IOT#2]
`Traceback (most recent call last):
  File "/home/mahmood/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1667, in create_block_manager_from_arrays
    mgr = BlockManager(blocks, axes)
  File "/home/mahmood/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 114, in __init__
    self._verify_integrity()
  File "/home/mahmood/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 311, in _verify_integrity
    construction_error(tot_items, block.shape[1:], self.axes)
  File "/home/mahmood/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1691, in construction_error
    passed, implied))
ValueError: Shape of passed values is (18000, 1), indices imply (1000, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hh.py", line 116, in <module>
    ECG = pd.DataFrame({'data' : L}, index=t_ECG)
  File "/home/mahmood/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 391, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/mahmood/.local/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/mahmood/.local/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 61, in arrays_to_mgr
    return create_block_manager_from_arrays(arrays, arr_names, axes)
  File "/home/mahmood/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1671, in create_block_manager_from_arrays
    construction_error(len(arrays), arrays[0].shape, axes, e)
  File "/home/mahmood/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1691, in construction_error
    passed, implied))
ValueError: Shape of passed values is (18000, 1), indices imply (1000, 1)
`

**Comment by sindhu9810** [comment]
same error im too getting
